# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classId', models.CharField(max_length=20)),
                ('className', models.CharField(max_length=20)),
                ('classClass', models.CharField(max_length=20)),
                ('academy', models.CharField(max_length=30)),
                ('credit', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseOnlyId', models.CharField(max_length=20)),
                ('userId', models.CharField(max_length=20)),
                ('callRate', models.IntegerField()),
                ('passRate', models.IntegerField()),
                ('getRate', models.IntegerField()),
                ('comment', models.TextField(max_length=300)),
                ('commentTime', models.DateTimeField()),
                ('ifPass', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseOnlyId', models.CharField(max_length=20)),
                ('classId', models.CharField(max_length=20)),
                ('teacherId', models.CharField(max_length=20)),
                ('className', models.CharField(max_length=20)),
                ('teacherName', models.CharField(max_length=20)),
                ('likes', models.IntegerField()),
                ('unlikes', models.IntegerField()),
                ('commentNum', models.IntegerField()),
                ('callRate', models.IntegerField()),
                ('passRate', models.IntegerField()),
                ('getRate', models.IntegerField()),
                ('clss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hbue.Clss')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=20)),
                ('courseOnlyId', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hbue.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherId', models.CharField(max_length=20)),
                ('teacherName', models.CharField(max_length=20)),
                ('teacherIcon', models.CharField(max_length=30)),
                ('teacherInfo', models.TextField(max_length=300)),
                ('course', models.ManyToManyField(through='hbue.Course', to='hbue.Clss')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=10)),
                ('userName', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('userIcon', models.CharField(max_length=30)),
                ('userInfo', models.CharField(max_length=300)),
                ('userAcademy', models.CharField(max_length=20)),
                ('userLevel', models.IntegerField()),
                ('course', models.ManyToManyField(through='hbue.Comment', to='hbue.Course')),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hbue.User'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_teacher', to='hbue.Teacher'),
        ),
        migrations.AddField(
            model_name='comment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hbue.Course'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hbue.User'),
        ),
    ]
