# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='classId',
        ),
        migrations.RemoveField(
            model_name='course',
            name='className',
        ),
        migrations.RemoveField(
            model_name='course',
            name='courseOnlyId',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacherId',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacherName',
        ),
        migrations.AlterField(
            model_name='course',
            name='callRate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='commentNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='getRate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='passRate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='unlikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacherIcon',
            field=models.CharField(default='/img/tdefaultIcon.jpg', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='userIcon',
            field=models.CharField(default='/img/udefaultIcon.jpg', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='userInfo',
            field=models.TextField(max_length=300),
        ),
    ]
