# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbue', '0003_auto_20171103_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='courseOnlyId',
        ),
        migrations.RemoveField(
            model_name='like',
            name='userId',
        ),
    ]
