# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbue', '0006_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lastRate',
            field=models.IntegerField(default=5),
        ),
    ]
