# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-04 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbue', '0007_course_lastrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userInfo',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userLevel',
            field=models.IntegerField(default=1),
        ),
    ]
