# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbue', '0009_auto_20171114_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userIcon',
            field=models.FileField(default='', upload_to='hbue/static/img/user/%m/%d'),
        ),
    ]
