# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbue', '0010_auto_20171114_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userIcon',
            field=models.FileField(default='hbue/static/img/penguin.png', upload_to='hbue/static/img/user/%m/%d'),
        ),
    ]
